#!/usr/bin/env python3
"""Build the new-chrome (Aug 18 capture) first-part flow assets:
  captures/sources-aug18/*.html  ->  src/data/newFlowHtml.js
  captures/sources-aug18/css/*   ->  src/styles/newflow-production.css (scoped under .nf)

Extraction is a balanced-tag scan (no external deps). CSS scoping prefixes every
selector with `.nf`, mapping html/body/:root tokens onto .nf itself, so the new
production CSS coexists with the old-era production.css already in this app.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'captures', 'sources-aug18')
OUT_JS = os.path.join(ROOT, 'src', 'data', 'newFlowHtml.js')
OUT_CSS = os.path.join(ROOT, 'src', 'styles', 'newflow-production.css')

VOID = {'area','base','br','col','embed','hr','img','input','link','meta','param','source','track','wbr'}

TAG_RE = re.compile(r'<(/?)([a-zA-Z][a-zA-Z0-9-]*)((?:"[^"]*"|\'[^\']*\'|[^>"\'])*)>')

def find_element(html, pred, start=0):
    """Return (s,e) outer bounds of first element whose open tag matches pred(tag, attrs)."""
    for m in TAG_RE.finditer(html, start):
        closing, tag, attrs = m.group(1), m.group(2).lower(), m.group(3)
        if closing or tag in VOID:
            continue
        if not pred(tag, attrs):
            continue
        # walk to balanced close
        depth = 0
        pos = m.start()
        for m2 in TAG_RE.finditer(html, m.start()):
            t2 = m2.group(2).lower()
            if t2 == 'script' and not m2.group(1):
                # skip script content wholesale
                endscript = html.find('</script>', m2.end())
                if endscript == -1: break
            if t2 != tag:
                continue
            if m2.group(1):
                depth -= 1
                if depth == 0:
                    return (m.start(), m2.end())
            elif not m2.group(3).rstrip().endswith('/'):
                depth += 1
        break
    return None

def outer(html, pred):
    r = find_element(html, pred)
    return html[r[0]:r[1]] if r else None

def absolutize(fragment):
    """Point root-relative asset refs at production so images/fonts resolve."""
    fragment = re.sub(r'(src|srcset|poster)="/(?!/)', r'\1="https://benable.com/', fragment)
    fragment = re.sub(r'url\((&quot;|"|\')?/(?!/)', lambda m: 'url(' + (m.group(1) or '') + 'https://benable.com/', fragment)
    return fragment

def js_template(s):
    return s.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')

# ---------- extraction ----------
states = {}
shell = {}
report = []
for fn in sorted(os.listdir(SRC)):
    if not fn.endswith('.html') or '.part' in fn:
        continue
    with open(os.path.join(SRC, fn), 'r', encoding='utf-8') as f:
        doc = f.read()
    key = fn[:-5]
    main = outer(doc, lambda t, a: t == 'main' and 'workspace-content' in a)
    # Modals render as body-level siblings AFTER the (empty) #rendered-modals
    # placeholder — take the whole tail up to </body>, scripts stripped.
    modal_inner = None
    wrap = find_element(doc, lambda t, a: t == 'div' and 'rendered-modals' in a)
    if wrap:
        tail = doc[wrap[1]:doc.rfind('</body>')]
        tail = re.sub(r'<script\b.*?</script>', '', tail, flags=re.S).strip()
        modal_inner = tail or None
    if not main:
        report.append(f'!! {key}: NO MAIN FOUND')
        continue
    states[key] = {
        'main': absolutize(main),
        'modal': absolutize(modal_inner) if modal_inner else None,
    }
    # settings/account-menu states also carry sidebar deltas (active item, menu popover)
    if key.startswith(('31-', '32-')):
        aside = outer(doc, lambda t, a: t == 'aside' and 'brand-workspace-sidebar' in a)
        if aside:
            states[key]['sidebar'] = absolutize(aside)
    report.append(f'{key}: main={len(main)}b modal={len(modal_inner) if modal_inner else 0}b')
    if key.startswith('01-'):
        shell['header'] = absolutize(outer(doc, lambda t, a: t == 'header' and 'mobile-header' in a) or '')
        shell['sidebar'] = absolutize(outer(doc, lambda t, a: t == 'aside' and 'brand-workspace-sidebar' in a) or '')
        bd = outer(doc, lambda t, a: t == 'button' and 'sidebar-backdrop' in a)
        shell['backdrop'] = absolutize(bd or '')

# ---------- write JS module ----------
with open(OUT_JS, 'w', encoding='utf-8') as f:
    f.write('// AUTO-GENERATED by scripts/newflow-build.py from captures/sources-aug18/ — do not hand-edit.\n')
    f.write('// Production capture of the create-campaign flow (new chrome), benable.com, Aug 18 2026.\n\n')
    f.write('export const NF_SHELL = {\n')
    for k in ('header', 'sidebar', 'backdrop'):
        f.write(f'  {k}: `{js_template(shell.get(k, ""))}`,\n')
    f.write('};\n\n')
    f.write('export const NF_STATES = {\n')
    for key, v in states.items():
        f.write(f'  {key!r}: {{\n    main: `{js_template(v["main"])}`,\n')
        if v['modal']:
            f.write(f'    modal: `{js_template(v["modal"])}`,\n')
        else:
            f.write('    modal: null,\n')
        if v.get('sidebar'):
            f.write(f'    sidebar: `{js_template(v["sidebar"])}`,\n')
        f.write('  },\n')
    f.write('};\n')

# ---------- CSS scoping ----------
CSS_ORDER = [
    'app.QMGREPde.css', 'tippy.LriLsbSV.css', '22.BwD2ib4K.css', 'Icon.CO1-JxUt.css',
    'NotificationToast.BAUi3w1E.css', 'BrandAvatar.B82KQGtX.css', 'pageAnimations.CXSQ1Y_U.css',
    'ajax.DclS4a0e.css', '135.BOp88lfA.css', 'ErrorState.C4KzLZgY.css', 'LoadingState.CpzVqq19.css',
    'close.DEhtbCLF.css', 'doka.80VQopet.css', 'BrandCampaignReviewContent.CDcqnX-w.css',
    'BrandCampaignDraftReviewPage.Cy6teKNr.css', 'editor.C4NaSJn3.css', 'file-upload.DM4rIr5j.css',
    '136.gqte2mkc.css', '137.I2vZ73Ud.css', 'all.min.css',
]
CDN_BASE = {'all.min.css': 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/'}
ASSET_BASE = 'https://benable.com/_app/immutable/assets/'

ROOTISH = re.compile(r'(?<![\w.#\[:-])(html|body|:root)(?![\w-])')

def split_selectors(prelude):
    out, depth, cur = [], 0, []
    for ch in prelude:
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        if ch == ',' and depth == 0:
            out.append(''.join(cur)); cur = []
        else:
            cur.append(ch)
    out.append(''.join(cur))
    return out

def scope_selector(sel):
    s = sel.strip()
    if not s:
        return s
    replaced = ROOTISH.sub('.nf', s)
    if '.nf' in replaced:
        return replaced
    return '.nf ' + replaced

def rewrite_urls(css, base):
    def fix(m):
        q, u = m.group(1) or '', m.group(2)
        if u.startswith(('data:', 'http', '#', 'https:')):
            return m.group(0)
        if u.startswith('//'):
            return f'url({q}https:{u}{q})'
        if u.startswith('/'):
            return f'url({q}https://benable.com{u}{q})'
        # relative
        u2 = u
        while u2.startswith('./'):
            u2 = u2[2:]
        b = base
        while u2.startswith('../'):
            u2 = u2[3:]
            b = b.rsplit('/', 2)[0] + '/'
        return f'url({q}{b}{u2}{q})'
    return re.sub(r'url\(\s*(["\']?)([^"\')]+)\1\s*\)', fix, css)

def scope_css(css):
    """Prefix all rule selectors with .nf. Recurses into conditional at-rules."""
    out, i, n = [], 0, len(css)
    while i < n:
        # skip whitespace + comments
        if css.startswith('/*', i):
            j = css.find('*/', i)
            i = n if j == -1 else j + 2
            continue
        if css[i] in ' \t\r\n':
            i += 1
            continue
        if css[i] == '@':
            # find prelude end — ';' or '{' only counts outside url(...) parens/quotes
            j = i
            depth0 = 0
            quote = None
            while j < n:
                c = css[j]
                if quote:
                    if c == quote:
                        quote = None
                elif c in '"\'':
                    quote = c
                elif c == '(':
                    depth0 += 1
                elif c == ')':
                    depth0 -= 1
                elif depth0 == 0 and c in '{;':
                    break
                j += 1
            at = css[i:j].strip()
            if j < n and css[j] == ';':
                if not at.startswith(('@charset', '@import')):
                    out.append(css[i:j + 1])
                i = j + 1
                continue
            # block at-rule: find matching brace
            depth, k = 0, j
            while k < n:
                if css[k] == '{':
                    depth += 1
                elif css[k] == '}':
                    depth -= 1
                    if depth == 0:
                        break
                k += 1
            body = css[j + 1:k]
            name = at.split('(')[0].split()[0]
            if name in ('@media', '@supports', '@container', '@layer'):
                out.append(f'{at}{{{scope_css(body)}}}')
            else:  # @keyframes/@font-face/@page etc: verbatim
                out.append(f'{at}{{{body}}}')
            i = k + 1
            continue
        # normal rule
        j = css.find('{', i)
        if j == -1:
            break
        depth, k = 0, j
        while k < n:
            if css[k] == '{':
                depth += 1
            elif css[k] == '}':
                depth -= 1
                if depth == 0:
                    break
            k += 1
        prelude = css[i:j]
        body = css[j + 1:k]
        scoped = ','.join(scope_selector(s) for s in split_selectors(prelude))
        out.append(f'{scoped}{{{body}}}')
        i = k + 1
    return ''.join(out)

pieces = [
    '/* AUTO-GENERATED by scripts/newflow-build.py — production CSS (Aug 18 capture) scoped under .nf */\n',
    # the inline <head> style from the captured pages (body font), scoped:
    ".nf{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,'Noto Sans',sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol','Noto Color Emoji' !important;}\n",
]
for fn in CSS_ORDER:
    path = os.path.join(SRC, 'css', fn)
    if not os.path.exists(path):
        report.append(f'!! css missing: {fn}')
        continue
    with open(path, 'r', encoding='utf-8') as f:
        css = f.read()
    base = CDN_BASE.get(fn, ASSET_BASE)
    css = rewrite_urls(css, base)
    scoped = scope_css(css)
    # National2Narrow (old-era font) appears only in unused decorative weights;
    # hotlinking it CORS-errors, so drop those @font-face blocks entirely.
    scoped = re.sub(r'@font-face\{[^}]*National2Narrow[^}]*\}', '', scoped)
    pieces.append(f'\n/* ==== {fn} ==== */\n' + scoped)

with open(OUT_CSS, 'w', encoding='utf-8') as f:
    f.write('\n'.join(pieces))

print('\n'.join(report))
print(f'\nwrote {OUT_JS} ({os.path.getsize(OUT_JS)} bytes)')
print(f'wrote {OUT_CSS} ({os.path.getsize(OUT_CSS)} bytes)')
